# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc4e0b0cc42daebbfc9cac8e2c5203e7d013a803480ff8ab2b231fdb340479b50ca87aed07f7b0839f2d0c5a68c578e54b5582058387fccc609f6f387cfe04f

test:
  secret_key_base: 9b705885fed9396f84a320f5723d6109dc61a485b4c05505921533fc65e622fd2f2e9bca3b4afa67eebc88e49143c5ec092faf7bb7a2d528fb4bdfad91dfabfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
